config/routes.rb
Loaner::Application.routes.draw do
  resources :people
  resources :books
  resources :lenders

  resource  :calculators do
    member do
      put 'calculate'
    end
  end
  resources :users
  resources :user_sessions
  resources :company_transactions do
    collection do
      get 'receipts'
      get 'payments'
      get 'repayments'
      get 'disbursements'
      get 'book_transfers'
      get 'account_transfers'
    end
  end
  resources :backups do
    collection do
      get 'backup'
      post 'restore'
    end
  end

  resources :company_configurations
  resources :company_profiles

  resources :transactions
  resources :loans do
    collection do
      get "calculate_payment_schedule"
    end
    resources :transactions
  end

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  namespace :settings do
    resources :user_rights
    root :to => "home#index"
  end

  namespace :reports do
    resources :payment_schedules
    resources :borrowers_lists, :only => [:index] do
      collection do
        get 'blacklisted'
        get 'alphabet'
      end
    end
    namespace :borrowers do
      resource :borrower_statements, :only => [:create,:show]
      resource :borrower_history, :controller => :borrower_history, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :for_submission do
      resource :monthly, :controller => :monthly, :only => [:show] do
        member do
          get 'main'
        end
      end
      namespace :quarterly do
        resource :loan_position, :controller => :loan_position, :only => :show
        resource :cash_position, :controller => :cash_position, :only => :show
        resource :receipts_and_payments, :only => :show
        root :to => "home#index"
      end
      root :to => "home#index"
    end
    namespace :for_records do
      resource :cash_account_books, :only => [:create,:show]
      resource :loan_account_books, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :for_governments do
      resource :statements, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :payment_due do
      resource :daily, :controller => :daily, :only => [:create,:show]
      resource :calendar_view, :controller => :calendar_view, :only => [:show]
      resource :aging, :controller => :aging, :only => [:show]
      root :to => "home#index"
    end

    namespace :book_statements do
      root :to => "home#index"
    end

    namespace :loan do
      resource :status, :controller => :status, :only => [:show] do
        member do
          get 'active'
          get 'closed'
        end
      end
    end
    root :to => "home#index"
  end

  namespace :admin do
    resources :company_profiles
    resources :users
    root :to => "home#index"
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_menu.html.haml
.menu_left
  %ul.menu_list
    - if current_user

      -#%li= link_to "Lenders", lenders_path
      -# if request[:controller] == "lender"
        %ul
          %li= link_to "New Lender", new_lender_path

      %li= link_to "Books", books_path
      - if request[:controller] == "Book"
        %ul
          %li= link_to "New Book", new_book_path

      %li= link_to "People", people_path
      - if request[:controller] == "people"
        %ul
          %li= link_to "New Person", new_person_path

      %li= link_to "Loans", loans_path
      - if request[:controller] == "loans"
        %ul
          %li= link_to "Loan Calculator", calculators_path
          %li= link_to "Loan Disbursement", new_loan_path
          %li= link_to "Collection", loans_path

      %li= link_to "Company Transactions", company_transactions_path
      - if request.env["PATH_INFO"] =~ /transaction/
        %ul
          %li= link_to "New Transaction", new_transaction_path
          %li= link_to "Receipts",      receipts_company_transactions_path
          %li= link_to "Payments",      payments_company_transactions_path
          %li= link_to "Repayments",    repayments_company_transactions_path
          %li= link_to "Disbursements", disbursements_company_transactions_path
          %li
            %span= "Book Transfer"
          %li
            %span= "Accounts"

      %li= link_to "Reports", reports_root_path
      - if request.env["PATH_INFO"] =~ /\/reports/
        %ul
          %li= link_to "Payment Schedule", reports_payment_schedules_path
          %li
            %span= "For Submission"
          %li
            %span= "For Records"
          %li
            %span= "Borrower Reports"
          %li= link_to "Borrowers List", reports_borrowers_lists_path
          %li
            %span= "Book Statements"
          %li
            %span= "Payment Due Report"
          %li
            %span= "Loan Status"

      %li= link_to "Settings", settings_root_path
      - if request.env["PATH_INFO"] =~ /\/settings/
        %ul
          %li= link_to "Company Profile", company_profiles_path
          %li= link_to "User Rights", settings_user_rights_path
          %li= link_to "Company Configuration", company_configurations_path
          %li= link_to "Client Details Modification", people_path


      %li= link_to "Logout", logout_path

    - else
      %li= link_to "Login", login_path
      %li= link_to "Register", new_user_path

app/views/shared/_print.html.haml
.nonprint
  - path = request.env["PATH_INFO"] + ".pdf"
  - unless request.env["QUERY_STRING"].blank?
    - path << "?" + request.env["QUERY_STRING"]
  = link_to "Download as pdf", path