config/routes.rb
Loaner::Application.routes.draw do
  resources :people
  resources :books
  resources :lenders

  resource  :calculators do
    member do
      put 'calculate'
    end
  end
  resources :users
  resources :user_sessions
  resources :company_transactions do
    collection do
      get 'receipts'
      get 'payments'
      get 'repayments'
      get 'disbursements'
      get 'book_transfers'
      get 'account_transfers'
    end
  end
  resources :backups do
    collection do
      get 'backup'
      post 'restore'
    end
  end

  resources :company_configurations
  resources :company_profiles

  resources :transactions
  resources :loans do
    collection do
      get "calculate_payment_schedule"
    end
    resources :transactions
  end

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  namespace :settings do
    resources :user_rights
    root :to => "home#index"
  end

  namespace :reports do
    resources :payment_schedules
    resources :borrowers_lists, :only => [:index] do
      collection do
        get 'blacklisted'
        get 'alphabet'
      end
    end
    namespace :borrowers do
      resource :borrower_statements, :only => [:create,:show]
      resource :borrower_history, :controller => :borrower_history, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :for_submission do
      resource :monthly, :controller => :monthly, :only => [:show] do
        member do
          get 'main'
        end
      end
      namespace :quarterly do
        resource :loan_position, :controller => :loan_position, :only => :show
        resource :cash_position, :controller => :cash_position, :only => :show
        resource :receipts_and_payments, :only => :show
        root :to => "home#index"
      end
      root :to => "home#index"
    end
    namespace :for_records do
      resource :cash_account_books, :only => [:create,:show]
      resource :loan_account_books, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :for_governments do
      resource :statements, :only => [:create,:show]
      root :to => "home#index"
    end
    namespace :payment_due do
      resource :daily, :controller => :daily, :only => [:create,:show]
      resource :calendar_view, :controller => :calendar_view, :only => [:show]
      resource :aging, :controller => :aging, :only => [:show]
      root :to => "home#index"
    end

    namespace :book_statements do
      root :to => "home#index"
    end

    namespace :loan do
      resource :status, :controller => :status, :only => [:show] do
        member do
          get 'active'
          get 'closed'
        end
      end
    end
    root :to => "home#index"
  end

  namespace :admin do
    resources :company_profiles
    resources :users
    root :to => "home#index"
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/transactions_controller.rb
class TransactionsController < InheritedResources::Base
  respond_to :html, :xml, :json
  belongs_to :loan#, :optional => true

  def create
    @transaction = Transaction.new params[:transaction].merge(:book => parent.book, :loan => parent)
    create! { return_path }
  end

  def update
    update! { return_path }
  end


#  # GET /transactions/receipts
#  def receipts
#    @receipts = Transaction.disbursements
#  end
# 
#  # GET /transactions/payments
#  def payments
#    @payments = Transaction.payments
#  end

  private

  def return_path
    @loan ? edit_loan_path(@loan) : transaction_path(@transaction)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= semantic_form_for [@loan, @transaction] do |form|
  = form.inputs do
    = form.error_messages
    = form.input :date, :as => :date_picker
    = form.input :receipt_no
    = form.input :amount
    = form.input :regular
    = form.input :principal
    = form.input :interest
    = form.input :late_interest
    = form.input :permitted_fee, :input_html => { :readonly => true }
    %a#show_permitted_fees{:href => "#"} Show Permitted Fees
    = form.inputs :id => :permitted_fees, :style => "display:none;" do
      = form.input :acceptance_fees
      = form.input :revolving_renewal_fees
      = form.input :late_repayment
      = form.input :terms_of_contract_variation
      = form.input :cheque_dishonour
      = form.input :preclosure_termination_fees
      = form.input :legal_fees
    = form.input :transaction_type, :as => :select, :collection => humanize(Transaction::LOAN_TRANSACTIONS), :include_blank => false
    = form.input :payment_type, :as => :select, :collection => humanize(Transaction::PAYMENT_TYPES), :include_blank => false
    -#= form.inputs  :name => "Loan", :id => "loan_group" do
      = form.input :target_loan, :as => :select, :collection => Loan.all, :include_blank => false
    -#= form.inputs  :name => "Book Transfer", :id => "book_transfer_group" do
      = form.input :src_book, :as => :select, :collection => current_user.books, :include_blank => false
      = form.input :dst_book, :as => :select, :collection => current_user.books, :include_blank => false
    -#= form.inputs  :name => "Account Transfer", :id => "account_transfer_group" do
      = form.input :src_account, :as => :select, :collection => User.all, :include_blank => false
      = form.input :dst_account, :as => :select, :collection => User.all, :include_blank => false
    = form.input :description, :as => :text
  = form.buttons do
    = form.commit_button

= javascript_include_tag "transactions"

app/views/transactions/edit.html.haml
- title "Edit Transaction Entry"
= render 'form'

app/views/transactions/index.html.haml
- title "Company Transactions"

app/views/transactions/new.html.haml
- title "New Transaction"
= render 'form'
%p= link_to "Back to Loan", @loan

app/views/transactions/payments.html.haml
- title "Payments"

%table.payments
  %tr
    %th Date
    %th Amount
    %th Loan
  - @payments.each do |payment|
    %tr
      %td= payment.paid_on
      %td= c payment.amount
      %td= link_to "Show Loan", edit_loan_path(payment.loan)

app/views/transactions/show.html.haml
- title "Transaction"

%p
  %strong Date:
  = @transaction.date
%p
  %strong Amount:
  = @transaction.amount
%p
  %strong Transaction Type:
  = @transaction.transaction_type
%p
  = link_to "Loan", loan_path(@transaction.loan)